### PR TITLE
#28: Add a "minage" feature

### PR DESCRIPTION
**Pull request by inikolaev**
This adds a `minage` directive which can be used to specify number minimum file age in days relative to current date.

It checks file modification time and only rotates file when it's old enough.

I also fixed some typos and some log message was missing `\n` at the end.
Added a bit more logging to debug mode and moved number of seconds in a day into a constant.

### CODE REVIEW

**Comment by kdudka** [comment]
I have rebased the above commits on top of current master:

https://github.com/logrotate/logrotate/compare/minage

Could you please have a look?

**Comment by kdudka** [comment]
@glensc Do you feel like doing a review of https://github.com/logrotate/logrotate/compare/minage?

**Comment by glensc** [comment]
@kdudka looks simple and good. did not spot any obvious mistakes. but didn't look closely the config parsing part. i assume it's just copy paste of similar parsing of other directives.

aside i noticed, #28 mentions about using seconds, but this PR (and your branch) min granularity is actually full days (can't even tweak to use `minage 0.5` to specify 12 hours :D).

anyway, LGTM for merge!

**Comment by kdudka** [comment]
On Thursday, September 08, 2016 12:36:49 Elan Ruusam�e wrote:
> @kdudka looks simple and good. did not spot any obvious mistakes. but didn't
> look closely the config parsing part. i assume it's just copy paste of
> similar parsing of other directives.

That was fast.  Thanks for review!

> aside i noticed, #28 mentions about using seconds, but this PR (and your
> branch) min granularity is actually full days (can't even tweak to use
> `minage 0.5` to specify 12 hours :D).

True.  But we have the same problem with the "maxage" directive already.

> anyway, LGTM for merge!

Perfect.  I will merge it then...

**Comment by tomaszpr** [comment]
Hi, in my opinion it doesn't work as expect.
According to code:

```
if (log->rotateMinAge && log->rotateMinAge >= (nowSecs - sb.st_mtime) / DAY_SECONDS) {
	    state->doRotate = 0;
	    message(MESS_DEBUG, "  log does not need rotating "
		    "('minage' directive is used and the log "
		    "age is smaller than the minage days)\n"); 

```
When I set minage 1, file will be rotated after 2 days, not after 1 day.

Example:
**rotateMinAge = 1**
Last file change: 12:00:00 
Current time:  12:01:00 next day
Time diff: 86400+60 > 1 day , in my opinion rotation should be done, but:
(nowSecs - sb.st_mtime) = 86400+60
(nowSecs - sb.st_mtime) / DAY_SECONDS = 1

if (rotateMinAge >= 1) !!!
state->doRotate = 0; DO NOT ROTATE!!!!

Rotation will be done after two all days, but I set minage 1.

**Comment by inikolaev** [comment]
I think you are right - it doesn't calculate age properly. I guess a better way would be:

```
log->rotateMinAge * DAY_SECONDS >= nowSecs - sb.st_mtime
```
in this case it would not be affected by this rounding issue.

**Comment by kdudka** [comment]
It makes sense to me.  @inikolaev should I push the change on your behalf?

**Comment by inikolaev** [comment]
Yes, go ahead @kdudka

**Pull request closed without merging**
