### PR TITLE
travis: add matrix to build with several gcc/clang versions

### PR DESCRIPTION
**Pull request by glensc**
to notice problems with different compilers, like #60

inspired by this post:
http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/

### CODE REVIEW

**Comment by glensc** [comment]
not sure why this build failed:
https://travis-ci.org/logrotate/logrotate/jobs/161453343

it succeeded on my branch:
https://travis-ci.org/glensc/logrotate/builds/161450721

maybe retry the build make error go away, i.e some kind of travis concurrency problem

**Comment by glensc** [comment]
neh. seems it's fine after merge:

https://travis-ci.org/logrotate/logrotate/builds/161615315

**Comment by kdudka** [comment]
The previous build failed because the automake macro ```AM_EXTRA_RECURSIVE_TARGETS``` was not expanded, most likely because an outdated version of automake was installed.  I am able to reproduce the failure while building from a fresh git clone on RHEL-6 with ```automake-1.11.1-4.el6```:
```
[kdudka@el6 ~]$ git clone https://github.com/logrotate/logrotate.git
Initialized empty Git repository in /home/kdudka/logrotate/.git/
remote: Counting objects: 2139, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 2139 (delta 4), reused 0 (delta 0), pack-reused 2128
Receiving objects: 100% (2139/2139), 455.68 KiB | 423 KiB/s, done.
Resolving deltas: 100% (1430/1430), done.

[kdudka@el6 ~]$ cd logrotate/
[kdudka@el6 logrotate]$ ./autogen.sh 
Preparing the logrotate build system...please wait

Found GNU Autoconf version 2.69
Found GNU Automake version 1.11.1
Found GNU Libtool version 2.2.6b

Automatically preparing build ... Warning: autoreconf failed
Attempting to run the preparation steps individually

Preparing build ... 
Warning: autoconf seems to have succeeded by removing the following options:
        AUTOCONF_OPTIONS="-f"

Removing those options should not be necessary and indicate some other
problem with the build system.  The build preparation is highly suspect
and may result in configuration or compilation errors.  Consider
rerunning the build preparation with verbose output enabled.
        ./autogen.sh --verbose

Continuing build preparation ... done

The logrotate build system is now prepared.  To build here, run:
  ./configure
  make

[kdudka@el6 logrotate]$ ./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
./configure: line 2618: syntax error near unexpected token `test'
./configure: line 2618: `AM_EXTRA_RECURSIVE_TARGETS(test)'
```

**Comment by glensc** [comment]
but why it fails randomly (err... that one time)? they do not have always same version of tools installed in travis?

**Comment by glensc** [comment]
seems the one that failed, just did not upgrade automake (the second install command), and no errors reported

the others (which succeeded) upgraded automake:
```
Preparing to replace automake 1:1.11.3-1ubuntu2 (using .../automake_1%3a1.14-0gnu2~12.04_all.deb) ...
Unpacking replacement automake ...
```

**Comment by kdudka** [comment]
If it was just a single random failure, it should be safe to ignore.  If the appears periodically, I would propose to just fix logrotate's build system such that it does not use the macro in question (thus does not require recent automake for build).

**Pull request closed without merging**
