### PR TITLE
big cleanup in handling SELinux context

### PR DESCRIPTION
**Pull request by kdudka**
Mainly code deduplication but also one bug fix:

If we use options 'compress' and 'sharedscripts' together, the rotated (and compressed) log files may end up with a wrong security context in case multiple files with different security contexts are rotated in a row.

### CODE REVIEW

**Comment by kdudka** [comment]
Rebased on top of current master branch...

**Comment by kdudka** [comment]
Rebased on top of current master branch...

**Comment by kdudka** [comment]
Rebased on top of current master branch...

**Comment by kdudka** [comment]
@glensc any comment on this PR?

**Comment by glensc** [comment]
@kdudka nope.

**Pull request closed without merging**
