### PR TITLE
logrotate.service: add hardening options

### PR DESCRIPTION
**Pull request by cgzones**
implements #141

### CODE REVIEW

**Comment by glensc** [comment]
could you provide link to documentation for each directive?

from name guessing i do see some issues:

- ProtectHome=true

may break logrotate configurations that rotate files in user's dir (example /home/tomcat/logs). but then maybe it shouldn't be rotated using system service?

- PrivateNetwork=true

this may break logrotate configurations to invoke `/bin/mail` to deliver mails, unless the `mail` command only queues locally. and of course all `action` blocks can contain basically anything may need network interaction. i guess it would be still fine if these settings are properly documented so people know where to look into and how to resolve issues.

**Comment by cgzones** [comment]
The directives can be found at: https://www.freedesktop.org/software/systemd/man/systemd.exec.html

You concerns might be correct, so an opt-in might be better.

**Comment by cgzones** [comment]
`ProtectKernelTunables=true` breaks SELinux support, cause it needs a writeable `/sys/fs/selinux`

**Comment by kdudka** [comment]
@cgzones Please let me know if you are fine with the requested changes.  I can squash them in for you if you agree.  No need to resubmit...

**Comment by cgzones** [comment]
since systemd v235 ProtectKernelTunables does not break SELinux anymore

**Comment by kdudka** [comment]
On Saturday, October 21, 2017 9:39:42 PM CET cgzones wrote:
> since systemd v235 ProtectKernelTunables does not break SELinux anymore

That is good.  But we cannot safely assume that users of logrotate run the 
latest version of systemd.  It is IMO better to keep the list of hardening 
options conservative than possibly break existing setups.

**Comment by kdudka** [comment]
@cgzones Please let me know if you are fine with the requested changes. I can squash them in for you if you agree. No need to resubmit...

**Comment by cgzones** [comment]
I am fine with the changes

**Comment by kdudka** [comment]
OK, merging now... Thanks!

**Pull request closed without merging**
