### PR TITLE
Add Shell linter - Differential-ShellCheck

### PR DESCRIPTION
**Pull request by jamacku**
Differential ShellCheck is a GitHub action that performs differential ShellCheck scans on files changed via PR and reports results directly in PR.

Since this repository contains a lot of shell scripts I think you might find it useful.

Documentation is available at: [@redhat-plumbers-in-action/differential-shellcheck](https://github.com/redhat-plumbers-in-action/differential-shellcheck#readme). Let me know If you are missing some feature or setting.

/cc @kdudka

### CODE REVIEW

**Review by kdudka — APPROVED** [review]
Works great.  Thanks!

**Comment by kdudka** [comment]
The only reported [issue](https://github.com/logrotate/logrotate/pull/456/files#diff-497d365c7d9aeb6ed3ed0c99ecf644f4279a6e9d24913b59da01c34eaebc0ee7) can be easily fixed:
```diff
--- a/test/test-common.sh
+++ b/test/test-common.sh
@@ -142,7 +142,7 @@ createlogs() {
 }

 checkmail() {
-    (echo -s $PWD/$1 user@invalid.; echo $2) | diff -u - mail-out
+    printf "%s\n%s\n" "-s $PWD/$1 user@invalid." "$2" | diff -u - mail-out
     if [ $? != 0 ]; then
         exit 5
     fi
```

I will open a separate pull request for it once this one is merged.  But the issue would not show up any more even without the fix because the check only reports changes introduced by pull requests.

**Comment by jamacku** [comment]
I have updated `SHA` of `differential-shellcheck` to the latest version.

Since you are using pining to `SHA`, I have added Dependabot to keep your workflows up to date.

**Comment by kdudka** [comment]
Thanks for the update!  Merging...

**Pull request closed without merging**
