### PR TITLE
Add GitHub Actions CI configuration

### PR DESCRIPTION
**Pull request by cgzones**
Covers compilers from Ubuntu 20.20 and Clang analysis and sanitizer jobs.
Drop the respective jobs from travis to reduce the load on them.

### CODE REVIEW

**Review by kdudka — APPROVED** [review]

**Comment by cgzones** [comment]
Rebased on top of #409.

**Comment by cgzones** [comment]
The builds on travis-ci.com have stopped due to a negative credit balance.
Should we bother requesting `OSS only credits` from their support or move completely to GitHub actions?

**Comment by cgzones** [comment]
The only downside is we are losing the build coverage of GCC versions prior version 7.

**Comment by kdudka** [comment]
Looks good but I cannot see any CI jobs associated with this pull request.  Do we yet need to enabled them somewhere?

> The only downside is we are losing the build coverage of GCC versions prior version 7.

That sounds acceptable to me.  The last supported release of GCC by upstream seems to be 9.4.

**Comment by cgzones** [comment]
GitHub Actions CI ran and succeeded on #430.
> Do we yet need to enable them somewhere?

I don't think so, probably just to avoid random pull requests mining crypto in added CI jobs.

**Comment by fabiang** [comment]
I think this PR fixed #405 :)

**Pull request merged**
