### PR TITLE
Allow to pass a home-relative path to include

### PR DESCRIPTION
**Pull request by cgzones**
Accept a path with leading "~/" in include directives and replace with the environment variable ${HOME} (if existent).

### CODE REVIEW

**Comment by kdudka** [comment]
This definitely needs to be documented.  Should we take the value from `getpwuid(getuid())->pw_dir` in case `$HOME` is unset to better emulate the tilde expansion in shell?

**Comment by dvzrv** [comment]
@cgzones thanks for looking into this and following up on #322.

I'm not familiar with the code base, but this looks like it will do what I envisioned in the issue.

**Comment by cgzones** [comment]
Updated.

Can you please either mention to keep the code ISO C90 compliant, e.g. in `CONTRIBUTING.md`, or add the warning `-Wdeclaration-after-statement`?

**Comment by kdudka** [comment]
@cgzones Pull request #328 enables the warning.

**Pull request closed without merging**
