### PR TITLE
ChangeLog.md: user-visible changes to appear in 3.22.0

### PR DESCRIPTION
**Pull request by cgzones**
Prepare a changelog entry for 3.22.0.

### CODE REVIEW

**Review by kdudka — APPROVED** [review]
Looks good.  Please do not forget to:
- update the `UNRELEASED` link in `ChangeLog.md`
- create the `3.22.0` link in `ChangeLog.md`
- update the `latest release` and `previous releases` sections in `README.md`

**Comment by cgzones** [comment]
I just released 3.22.0.
I would appreciate a short look if everything is updated correctly.

**Comment by kdudka** [comment]
@cgzones Perfect, thank you for taking care of it!  I think we should update the [Verify and unpack](https://github.com/logrotate/logrotate?tab=readme-ov-file#verify-and-unpack) section of the top-level `README.md` file so that downstream consumers can easily verify signatures of the distribution tarballs.

**Comment by kdudka** [comment]
> I think we should update the [Verify and unpack](https://github.com/logrotate/logrotate?tab=readme-ov-file#verify-and-unpack) section of the top-level README.md file so that downstream consumers can easily verify signatures of the distribution tarballs.

I can see this has already been reported as #611.

**Pull request closed without merging**
